### ISSUE TITLE
Incorrect chapter sorting 

### ISSUE THREAD

**Issue by phenomen** [bdsqqq/psykip#2]
It should be `1, 2, 3...` but it's `1, 10, 11...`

**Comment by bdsqqq** [comment]
@phenomen Thank you! This bug is probably a consequence of an update we've made to the way we consume the translation files; Will look into it ASAP

**Comment by Timbwa** [comment]
Hey, coming from Twitter, but isn't 1, 2, 3  1, 10, 11 in binary?

**Comment by bdsqqq** [comment]
@Timbwa It is!

We considered closing this issue without a fix because of this fact. 
After excruciating research, we found that the canonical order in the original books is not in binary tho. 

We'll keep the order  `1, 2, 3...` until the Author releases a new edition of the book with modified ordering.
